
#include "main.h"

/**
 *  tell the compiler that the get_module is a pure C function
 */
extern "C"
{

	/**
	 *  Function that is called by PHP right after the PHP process has started, and that returns an address of an internal PHP
	 *  strucure with all the details and features of your extension
	 */
	PHPCPP_EXPORT void *get_module()
	{
		// static(!) Php::Extension object that should stay in memory for the entire duration of the process (that's why it's static)
		static Php::Extension extension("gtk3", "1.0");

		// GObject
		Php::Class<GObject_> gobject("GObject");
			gobject.method<&GObject_::connect>("connect");
			gobject.method<&GObject_::connect_after>("connect_after");
			gobject.method<&GObject_::handler_disconnect>("handler_disconnect");
			gobject.method<&GObject_::is_connected>("is_connected");
			gobject.method<&GObject_::get_property>("get_property");
			gobject.method<&GObject_::set_property>("set_property");
			gobject.method<&GObject_::signal_handler_block>("signal_handler_block");
			gobject.method<&GObject_::signal_handler_unblock>("signal_handler_unblock");
			gobject.constant("TYPE_INVALID", (int)G_TYPE_INVALID);
			gobject.constant("TYPE_NONE", (int)G_TYPE_NONE);
			gobject.constant("TYPE_INTERFACE", (int)G_TYPE_INTERFACE);
			gobject.constant("TYPE_CHAR", (int)G_TYPE_CHAR);
			gobject.constant("TYPE_UCHAR", (int)G_TYPE_UCHAR);
			gobject.constant("TYPE_BOOLEAN", (int)G_TYPE_BOOLEAN);
			gobject.constant("TYPE_INT", (int)G_TYPE_INT);
			gobject.constant("TYPE_UINT", (int)G_TYPE_UINT);
			gobject.constant("TYPE_LONG", (int)G_TYPE_LONG);
			gobject.constant("TYPE_ULONG", (int)G_TYPE_ULONG);
			gobject.constant("TYPE_INT64", (int)G_TYPE_INT64);
			gobject.constant("TYPE_UINT64", (int)G_TYPE_UINT64);
			gobject.constant("TYPE_ENUM", (int)G_TYPE_ENUM);
			gobject.constant("TYPE_FLAGS", (int)G_TYPE_FLAGS);
			gobject.constant("TYPE_FLOAT", (int)G_TYPE_FLOAT);
			gobject.constant("TYPE_DOUBLE", (int)G_TYPE_DOUBLE);
			gobject.constant("TYPE_STRING", (int)G_TYPE_STRING);
			gobject.constant("TYPE_PIXBUF", (int)GDK_TYPE_PIXBUF);
			gobject.constant("TYPE_POINTER", (int)G_TYPE_POINTER);
			gobject.constant("TYPE_BOXED", (int)G_TYPE_BOXED);
			gobject.constant("TYPE_PARAM", (int)G_TYPE_PARAM);
			gobject.constant("TYPE_OBJECT", (int)G_TYPE_OBJECT);
			gobject.constant("TYPE_GTYPE", (int)G_TYPE_GTYPE);
			gobject.constant("TYPE_VARIANT", (int)G_TYPE_VARIANT);
			gobject.constant("TYPE_CHECKSUM", (int)G_TYPE_CHECKSUM);

		
		Php::Class<GtkWidget_> gtkwidget("GtkWidget");
            gtkwidget.extends(gobject);
			gtkwidget.method<&GtkWidget_::destroy>("destroy");
			gtkwidget.method<&GtkWidget_::destroyed>("destroyed");
			gtkwidget.method<&GtkWidget_::unparent>("unparent");
			gtkwidget.method<&GtkWidget_::show>("show");
			gtkwidget.method<&GtkWidget_::hide>("hide");
			gtkwidget.method<&GtkWidget_::show_now>("show_now");
			gtkwidget.method<&GtkWidget_::show_all>("show_all");
			gtkwidget.method<&GtkWidget_::set_no_show_all>("set_no_show_all");
			gtkwidget.method<&GtkWidget_::get_no_show_all>("get_no_show_all");
			gtkwidget.method<&GtkWidget_::map>("map");
			gtkwidget.method<&GtkWidget_::unmap>("unmap");
			gtkwidget.method<&GtkWidget_::realize>("realize");
			gtkwidget.method<&GtkWidget_::unrealize>("unrealize");
			gtkwidget.method<&GtkWidget_::draw>("draw");
			gtkwidget.method<&GtkWidget_::queue_draw>("queue_draw");
			gtkwidget.method<&GtkWidget_::queue_draw_area>("queue_draw_area");
			gtkwidget.method<&GtkWidget_::queue_resize>("queue_resize");
			gtkwidget.method<&GtkWidget_::queue_resize_no_redraw>("queue_resize_no_redraw");
			gtkwidget.method<&GtkWidget_::queue_allocate>("queue_allocate");
			gtkwidget.method<&GtkWidget_::get_request_mode>("get_request_mode");
			gtkwidget.method<&GtkWidget_::get_preferred_width>("get_preferred_width");
			gtkwidget.method<&GtkWidget_::get_preferred_height_for_width>("get_preferred_height_for_width");
			gtkwidget.method<&GtkWidget_::get_preferred_height>("get_preferred_height");
			gtkwidget.method<&GtkWidget_::get_preferred_width_for_height>("get_preferred_width_for_height");
			gtkwidget.method<&GtkWidget_::get_preferred_height_and_baseline_for_width>("get_preferred_height_and_baseline_for_width");
			gtkwidget.method<&GtkWidget_::add_accelerator>("add_accelerator");
			gtkwidget.method<&GtkWidget_::remove_accelerator>("remove_accelerator");
			gtkwidget.method<&GtkWidget_::set_accel_path>("set_accel_path");
			gtkwidget.method<&GtkWidget_::list_accel_closures>("list_accel_closures");
			gtkwidget.method<&GtkWidget_::can_activate_accel>("can_activate_accel");
			gtkwidget.method<&GtkWidget_::mnemonic_activate>("mnemonic_activate");
			gtkwidget.method<&GtkWidget_::activate>("activate");
			gtkwidget.method<&GtkWidget_::reparent>("reparent");
			gtkwidget.method<&GtkWidget_::freeze_child_notify>("freeze_child_notify");
			gtkwidget.method<&GtkWidget_::child_notify>("child_notify");
			gtkwidget.method<&GtkWidget_::thaw_child_notify>("thaw_child_notify");
			gtkwidget.method<&GtkWidget_::set_can_focus>("set_can_focus");
			gtkwidget.method<&GtkWidget_::get_can_focus>("get_can_focus");
			gtkwidget.method<&GtkWidget_::has_focus>("has_focus");
			gtkwidget.method<&GtkWidget_::is_focus>("is_focus");
			gtkwidget.method<&GtkWidget_::has_visible_focus>("has_visible_focus");
			gtkwidget.method<&GtkWidget_::grab_focus>("grab_focus");
			gtkwidget.method<&GtkWidget_::set_focus_on_click>("set_focus_on_click");
			gtkwidget.method<&GtkWidget_::get_focus_on_click>("get_focus_on_click");
			gtkwidget.method<&GtkWidget_::set_can_default>("set_can_default");
			gtkwidget.method<&GtkWidget_::get_can_default>("get_can_default");
			gtkwidget.method<&GtkWidget_::has_default>("has_default");
			gtkwidget.method<&GtkWidget_::grab_default>("grab_default");
			gtkwidget.method<&GtkWidget_::set_receives_default>("set_receives_default");
			gtkwidget.method<&GtkWidget_::get_receives_default>("get_receives_default");
			gtkwidget.method<&GtkWidget_::has_grab>("has_grab");
			gtkwidget.method<&GtkWidget_::device_is_shadowed>("device_is_shadowed");
			gtkwidget.method<&GtkWidget_::set_name>("set_name");
			gtkwidget.method<&GtkWidget_::get_name>("get_name");
			gtkwidget.method<&GtkWidget_::set_state>("set_state");
			gtkwidget.method<&GtkWidget_::get_state>("get_state");
			gtkwidget.method<&GtkWidget_::set_state_flags>("set_state_flags");
			gtkwidget.method<&GtkWidget_::unset_state_flags>("unset_state_flags");
			gtkwidget.method<&GtkWidget_::get_state_flags>("get_state_flags");
			gtkwidget.method<&GtkWidget_::set_sensitive>("set_sensitive");
			gtkwidget.method<&GtkWidget_::get_sensitive>("get_sensitive");
			gtkwidget.method<&GtkWidget_::is_sensitive>("is_sensitive");
			gtkwidget.method<&GtkWidget_::set_visible>("set_visible");
			gtkwidget.method<&GtkWidget_::get_visible>("get_visible");
			gtkwidget.method<&GtkWidget_::is_visible>("is_visible");
			gtkwidget.method<&GtkWidget_::set_has_window>("set_has_window");
			gtkwidget.method<&GtkWidget_::get_has_window>("get_has_window");
			gtkwidget.method<&GtkWidget_::is_toplevel>("is_toplevel");
			gtkwidget.method<&GtkWidget_::is_drawable>("is_drawable");
			gtkwidget.method<&GtkWidget_::set_realized>("set_realized");
			gtkwidget.method<&GtkWidget_::get_realized>("get_realized");
			gtkwidget.method<&GtkWidget_::set_mapped>("set_mapped");
			gtkwidget.method<&GtkWidget_::get_mapped>("get_mapped");
			gtkwidget.method<&GtkWidget_::set_app_paintable>("set_app_paintable");
			gtkwidget.method<&GtkWidget_::get_app_paintable>("get_app_paintable");
			gtkwidget.method<&GtkWidget_::set_double_buffered>("set_double_buffered");
			gtkwidget.method<&GtkWidget_::get_double_buffered>("get_double_buffered");
			gtkwidget.method<&GtkWidget_::set_redraw_on_allocate>("set_redraw_on_allocate");
			gtkwidget.method<&GtkWidget_::set_parent>("set_parent");
			gtkwidget.method<&GtkWidget_::get_parent>("get_parent");
			gtkwidget.method<&GtkWidget_::set_parent_window>("set_parent_window");
			gtkwidget.method<&GtkWidget_::get_parent_window>("get_parent_window");
			gtkwidget.method<&GtkWidget_::set_child_visible>("set_child_visible");
			gtkwidget.method<&GtkWidget_::get_child_visible>("get_child_visible");
			gtkwidget.method<&GtkWidget_::set_window>("set_window");
			gtkwidget.method<&GtkWidget_::get_window>("get_window");
			gtkwidget.method<&GtkWidget_::register_window>("register_window");
			gtkwidget.method<&GtkWidget_::unregister_window>("unregister_window");
			gtkwidget.method<&GtkWidget_::get_allocated_width>("get_allocated_width");
			gtkwidget.method<&GtkWidget_::get_allocated_height>("get_allocated_height");
			gtkwidget.method<&GtkWidget_::get_allocated_baseline>("get_allocated_baseline");
			gtkwidget.method<&GtkWidget_::get_allocated_size>("get_allocated_size");
			gtkwidget.method<&GtkWidget_::get_allocation>("get_allocation");
			gtkwidget.method<&GtkWidget_::set_allocation>("set_allocation");
			gtkwidget.method<&GtkWidget_::set_clip>("set_clip");
			gtkwidget.method<&GtkWidget_::get_clip>("get_clip");
			gtkwidget.method<&GtkWidget_::get_requisition>("get_requisition");
			gtkwidget.method<&GtkWidget_::child_focus>("child_focus");
			gtkwidget.method<&GtkWidget_::keynav_failed>("keynav_failed");
			gtkwidget.method<&GtkWidget_::error_bell>("error_bell");
			gtkwidget.method<&GtkWidget_::set_size_request>("set_size_request");
			gtkwidget.method<&GtkWidget_::get_size_request>("get_size_request");
			gtkwidget.method<&GtkWidget_::set_events>("set_events");
			gtkwidget.method<&GtkWidget_::add_events>("add_events");
			gtkwidget.method<&GtkWidget_::set_device_events>("set_device_events");
			gtkwidget.method<&GtkWidget_::add_device_events>("add_device_events");
			gtkwidget.method<&GtkWidget_::set_opacity>("set_opacity");
			gtkwidget.method<&GtkWidget_::get_opacity>("get_opacity");
			gtkwidget.method<&GtkWidget_::set_device_enabled>("set_device_enabled");
			gtkwidget.method<&GtkWidget_::get_device_enabled>("get_device_enabled");
			gtkwidget.method<&GtkWidget_::get_toplevel>("get_toplevel");
			gtkwidget.method<&GtkWidget_::get_ancestor>("get_ancestor");
			gtkwidget.method<&GtkWidget_::get_visual>("get_visual");
			gtkwidget.method<&GtkWidget_::set_visual>("set_visual");
			gtkwidget.method<&GtkWidget_::get_screen>("get_screen");
			gtkwidget.method<&GtkWidget_::has_screen>("has_screen");
			gtkwidget.method<&GtkWidget_::get_scale_factor>("get_scale_factor");
			gtkwidget.method<&GtkWidget_::get_display>("get_display");
			gtkwidget.method<&GtkWidget_::get_root_window>("get_root_window");
			gtkwidget.method<&GtkWidget_::get_settings>("get_settings");
			gtkwidget.method<&GtkWidget_::get_hexpand>("get_hexpand");
			gtkwidget.method<&GtkWidget_::set_hexpand>("set_hexpand");
			gtkwidget.method<&GtkWidget_::get_hexpand_set>("get_hexpand_set");
			gtkwidget.method<&GtkWidget_::set_hexpand_set>("set_hexpand_set");
			gtkwidget.method<&GtkWidget_::get_vexpand>("get_vexpand");
			gtkwidget.method<&GtkWidget_::set_vexpand>("set_vexpand");
			gtkwidget.method<&GtkWidget_::get_vexpand_set>("get_vexpand_set");
			gtkwidget.method<&GtkWidget_::set_vexpand_set>("set_vexpand_set");
			gtkwidget.method<&GtkWidget_::queue_compute_expand>("queue_compute_expand");
			gtkwidget.method<&GtkWidget_::compute_expand>("compute_expand");
			gtkwidget.method<&GtkWidget_::get_support_multidevice>("get_support_multidevice");
			gtkwidget.method<&GtkWidget_::set_support_multidevice>("set_support_multidevice");
			gtkwidget.method<&GtkWidget_::get_halign>("get_halign");
			gtkwidget.method<&GtkWidget_::set_halign>("set_halign");
			gtkwidget.method<&GtkWidget_::get_valign>("get_valign");
			gtkwidget.method<&GtkWidget_::get_valign_with_baseline>("get_valign_with_baseline");
			gtkwidget.method<&GtkWidget_::set_valign>("set_valign");
			gtkwidget.method<&GtkWidget_::get_margin_left>("get_margin_left");
			gtkwidget.method<&GtkWidget_::set_margin_left>("set_margin_left");
			gtkwidget.method<&GtkWidget_::get_margin_right>("get_margin_right");
			gtkwidget.method<&GtkWidget_::set_margin_right>("set_margin_right");
			gtkwidget.method<&GtkWidget_::get_margin_start>("get_margin_start");
			gtkwidget.method<&GtkWidget_::set_margin_start>("set_margin_start");
			gtkwidget.method<&GtkWidget_::get_margin_end>("get_margin_end");
			gtkwidget.method<&GtkWidget_::set_margin_end>("set_margin_end");
			gtkwidget.method<&GtkWidget_::get_margin_top>("get_margin_top");
			gtkwidget.method<&GtkWidget_::set_margin_top>("set_margin_top");
			gtkwidget.method<&GtkWidget_::get_margin_bottom>("get_margin_bottom");
			gtkwidget.method<&GtkWidget_::set_margin_bottom>("set_margin_bottom");
			gtkwidget.method<&GtkWidget_::get_events>("get_events");
			gtkwidget.method<&GtkWidget_::get_device_events>("get_device_events");
			gtkwidget.method<&GtkWidget_::get_pointer>("get_pointer");
			gtkwidget.method<&GtkWidget_::is_ancestor>("is_ancestor");
			gtkwidget.method<&GtkWidget_::hide_on_delete>("hide_on_delete");
			gtkwidget.method<&GtkWidget_::override_color>("override_color");
			gtkwidget.method<&GtkWidget_::override_background_color>("override_background_color");
			gtkwidget.method<&GtkWidget_::override_font>("override_font");
			gtkwidget.method<&GtkWidget_::override_symbolic_color>("override_symbolic_color");
			gtkwidget.method<&GtkWidget_::override_cursor>("override_cursor");
			gtkwidget.method<&GtkWidget_::reset_style>("reset_style");
			gtkwidget.method<&GtkWidget_::set_font_options>("set_font_options");
			gtkwidget.method<&GtkWidget_::render_icon_pixbuf>("render_icon_pixbuf");
			gtkwidget.method<&GtkWidget_::set_composite_name>("set_composite_name");
			gtkwidget.method<&GtkWidget_::get_composite_name>("get_composite_name");
			gtkwidget.method<&GtkWidget_::set_direction>("set_direction");
			gtkwidget.method<&GtkWidget_::get_direction>("get_direction");
			gtkwidget.method<&GtkWidget_::is_composited>("is_composited");
			gtkwidget.method<&GtkWidget_::list_mnemonic_labels>("list_mnemonic_labels");
			gtkwidget.method<&GtkWidget_::add_mnemonic_label>("add_mnemonic_label");
			gtkwidget.method<&GtkWidget_::remove_mnemonic_label>("remove_mnemonic_label");
			gtkwidget.method<&GtkWidget_::set_tooltip_window>("set_tooltip_window");
			gtkwidget.method<&GtkWidget_::get_tooltip_window>("get_tooltip_window");
			gtkwidget.method<&GtkWidget_::trigger_tooltip_query>("trigger_tooltip_query");
			gtkwidget.method<&GtkWidget_::set_tooltip_text>("set_tooltip_text");
			gtkwidget.method<&GtkWidget_::get_tooltip_text>("get_tooltip_text");
			gtkwidget.method<&GtkWidget_::set_tooltip_markup>("set_tooltip_markup");
			gtkwidget.method<&GtkWidget_::get_tooltip_markup>("get_tooltip_markup");
			gtkwidget.method<&GtkWidget_::set_has_tooltip>("set_has_tooltip");
			gtkwidget.method<&GtkWidget_::get_has_tooltip>("get_has_tooltip");
			gtkwidget.method<&GtkWidget_::in_destruction>("in_destruction");
			gtkwidget.method<&GtkWidget_::get_style_context>("get_style_context");
			gtkwidget.method<&GtkWidget_::get_modifier_mask>("get_modifier_mask");
			gtkwidget.method<&GtkWidget_::init_template>("init_template");
			gtkwidget.method<&GtkWidget_::style_attach>("style_attach");
			gtkwidget.method<&GtkWidget_::has_rc_style>("has_rc_style");
			gtkwidget.method<&GtkWidget_::set_style>("set_style");
			gtkwidget.method<&GtkWidget_::ensure_style>("ensure_style");
			gtkwidget.method<&GtkWidget_::get_style>("get_style");
			gtkwidget.method<&GtkWidget_::modify_style>("modify_style");
			gtkwidget.method<&GtkWidget_::get_modifier_style>("get_modifier_style");
			gtkwidget.method<&GtkWidget_::modify_fg>("modify_fg");
			gtkwidget.method<&GtkWidget_::modify_bg>("modify_bg");
			gtkwidget.method<&GtkWidget_::modify_text>("modify_text");
			gtkwidget.method<&GtkWidget_::modify_base>("modify_base");
			gtkwidget.method<&GtkWidget_::modify_cursor>("modify_cursor");
			gtkwidget.method<&GtkWidget_::reset_rc_styles>("reset_rc_styles");
			gtkwidget.method<&GtkWidget_::render_icon>("render_icon");
			gtkwidget.method<&GtkWidget_::__construct>("__construct");

		extension.add(std::move(gobject));
		
		extension.add(std::move(gtkwidget));

		return extension;
	}
}